[2021-02-28 09:18:03,992] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ga_to_postgres_dag.store_ga_csv 2021-02-28T08:10:00+00:00 [queued]>
[2021-02-28 09:18:03,997] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ga_to_postgres_dag.store_ga_csv 2021-02-28T08:10:00+00:00 [queued]>
[2021-02-28 09:18:03,997] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-28 09:18:03,997] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-28 09:18:03,997] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-28 09:18:04,003] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): store_ga_csv> on 2021-02-28T08:10:00+00:00
[2021-02-28 09:18:04,004] {standard_task_runner.py:52} INFO - Started process 35251 to run task
[2021-02-28 09:18:04,011] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ga_to_postgres_dag', 'store_ga_csv', '2021-02-28T08:10:00+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ga_to_postgres_dag.py', '--cfg-path', '/var/folders/fh/z0rf64gj7d93005s7pxrkwm40000gn/T/tmpihfbntzz', '--error-file', '/var/folders/fh/z0rf64gj7d93005s7pxrkwm40000gn/T/tmp3wt0hbit']
[2021-02-28 09:18:04,012] {standard_task_runner.py:77} INFO - Job 18: Subtask store_ga_csv
[2021-02-28 09:18:04,044] {logging_mixin.py:104} INFO - Running <TaskInstance: ga_to_postgres_dag.store_ga_csv 2021-02-28T08:10:00+00:00 [running]> on host 120.0.168.192.in-addr.arpa
[2021-02-28 09:18:04,068] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ga_to_postgres_dag
AIRFLOW_CTX_TASK_ID=store_ga_csv
AIRFLOW_CTX_EXECUTION_DATE=2021-02-28T08:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-28T08:10:00+00:00
[2021-02-28 09:18:04,068] {logging_mixin.py:104} INFO - save_data_csv
[2021-02-28 09:18:04,069] {python.py:118} INFO - Done. Returned value was: None
[2021-02-28 09:18:04,073] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=ga_to_postgres_dag, task_id=store_ga_csv, execution_date=20210228T081000, start_date=20210228T081803, end_date=20210228T081804
[2021-02-28 09:18:04,086] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-28 09:18:04,108] {local_task_job.py:146} INFO - Task exited with return code 0
