[2021-02-28 09:18:01,535] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ga_to_postgres_dag.check_api 2021-02-28T08:10:00+00:00 [queued]>
[2021-02-28 09:18:01,539] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ga_to_postgres_dag.check_api 2021-02-28T08:10:00+00:00 [queued]>
[2021-02-28 09:18:01,539] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-28 09:18:01,539] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-28 09:18:01,540] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-28 09:18:01,545] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): check_api> on 2021-02-28T08:10:00+00:00
[2021-02-28 09:18:01,547] {standard_task_runner.py:52} INFO - Started process 35247 to run task
[2021-02-28 09:18:01,554] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ga_to_postgres_dag', 'check_api', '2021-02-28T08:10:00+00:00', '--job-id', '16', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ga_to_postgres_dag.py', '--cfg-path', '/var/folders/fh/z0rf64gj7d93005s7pxrkwm40000gn/T/tmp3up12_ja', '--error-file', '/var/folders/fh/z0rf64gj7d93005s7pxrkwm40000gn/T/tmpu32735mw']
[2021-02-28 09:18:01,556] {standard_task_runner.py:77} INFO - Job 16: Subtask check_api
[2021-02-28 09:18:01,588] {logging_mixin.py:104} INFO - Running <TaskInstance: ga_to_postgres_dag.check_api 2021-02-28T08:10:00+00:00 [running]> on host 120.0.168.192.in-addr.arpa
[2021-02-28 09:18:01,614] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ga_to_postgres_dag
AIRFLOW_CTX_TASK_ID=check_api
AIRFLOW_CTX_EXECUTION_DATE=2021-02-28T08:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-28T08:10:00+00:00
[2021-02-28 09:18:01,615] {logging_mixin.py:104} INFO - check api
[2021-02-28 09:18:01,615] {python.py:118} INFO - Done. Returned value was: None
[2021-02-28 09:18:01,619] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=ga_to_postgres_dag, task_id=check_api, execution_date=20210228T081000, start_date=20210228T081801, end_date=20210228T081801
[2021-02-28 09:18:01,632] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-28 09:18:01,653] {local_task_job.py:146} INFO - Task exited with return code 0
